version: '3'
services:
  coredns:
    image: coredns/coredns:latest
    container_name: coredns
    ports:
      - "53:53/udp"  # DNS port 53 for UDP requests
    volumes:
      - ./Corefile:/etc/coredns/Corefile  # Configuration file for CoreDNS
    networks:
      - cdn-network

  load-balancer-1:
    image: nginx:latest
    container_name: load-balancer-1
    ports:
      - "8081:80"  # Port forwarding for the first load balancer
    volumes:
      - ./nginx-lb1.conf:/etc/nginx/nginx.conf  # Configuration for Round Robin load balancing
    depends_on:
      - coredns
      - node1
      - node2
    networks:
      - cdn-network

  load-balancer-2:
    image: nginx:latest
    container_name: load-balancer-2
    ports:
      - "8082:80"  # Port forwarding for the second load balancer
    volumes:
      - ./nginx-lb2.conf:/etc/nginx/nginx.conf  # Configuration for Weighted Round Robin load balancing
    depends_on:
      - coredns
      - node3
      - node4
    networks:
      - cdn-network

  node1:
    build:
      context: ./node1
    container_name: node1
    ports:
      - "8083:80"
    networks:
      - cdn-network

  node2:
    build:
      context: ./node2
    container_name: node2
    ports:
      - "8084:80"
    networks:
      - cdn-network

  node3:
    build:
      context: ./node3
    container_name: node3
    ports:
      - "8085:80"
    networks:
      - cdn-network

  node4:
    build:
      context: ./node4
    container_name: node4
    ports:
      - "8086:80"
    networks:
      - cdn-network

networks:
  cdn-network:
    driver: bridge
